App can now properly distinguish between online users
Pem-Med/pem-app pull request #44
Opened 2021-03-26 00:39 UTC by Winterlord8

Hijacked FirebaseAuth onAuthStateChanged function to track when a user is online or not, changes are made to the onlineUsers database.

2021-03-26 01:16 UTC, vrivero09 approved these changes
Looks good! Should try to remove the unnecessary usernames so we can get an accurate list.

2021-03-29 20:17 UTC, vrive approved these changes
Works great!
Just make sure to remove old code that you dont use and also undo the change you made to the 'getImageRemoteUri' function

2021-03-29 20:17 UTC, vrive commented on backend/firebase.js
> +  const photoPath = `uploads/${Date.now()}.jpg`;
change this back please!

const photoPath = `uploads/${firebase.auth().currentUser.uid}/${cme.id}.jpg`;

2021-03-31 18:38 UTC, vrive commented
can you run 'git pull origin master' and then 'npm install' and then push? I think that might help with the conflict

2021-04-02 13:02 UTC, vrivero09 requested changes
Reviewing the request and when I go to profile>CME screen, it gives me an error about the certs. Just need to delete all certs definition in profile and login screen and leave the navigation to cme in profile by itself:

line 89

  const handleCerts = () => {
    props.navigation.navigate('CME')
  }

2021-04-05 19:52 UTC, vrivero09 approved these changes

2021-04-05 19:53 UTC, merged